import sys
import re
from pathlib import Path
import pydicom
from pydicom.errors import InvalidDicomError


# ---------------------------------------------------------------------------
# Known anonymised placeholder values per tag.
# If a tag's value matches any entry here it is considered clean.
# All comparisons are case-insensitive / stripped.
# ---------------------------------------------------------------------------
ANON_NAME_TOKENS = {
    "anonymous", "anon", "anonymized", "anonymised",
    "unknown", "removed", "deleted", "redacted",
    "patient", "none", "na", "n/a", "",
}

# Sex: O = "Other" is the standard DICOM placeholder for anonymised sex
ANON_SEX_VALUES = {"o", ""}

# Generic placeholder strings used in free-text / ID fields
ANON_GENERIC_TOKENS = {
    "anonymous", "anon", "anonymized", "anonymised",
    "unknown", "removed", "deleted", "redacted",
    "none", "na", "n/a", "",
}


def looks_like_real_name(value: str) -> bool:
    """
    Return True if the value looks like a real patient name rather than a placeholder.
    DICOM names use caret-separated components: Family^Given^Middle^Prefix^Suffix
    """
    cleaned = value.strip().lower()
    # Strip caret separators and check each component
    parts = [p.strip() for p in re.split(r"[\^]+", cleaned) if p.strip()]
    if not parts:
        return False
    # If every non-empty component is a known placeholder token → clean
    return not all(p in ANON_NAME_TOKENS for p in parts)


def looks_like_real_id(value: str) -> bool:
    """Return True if the value looks like a real patient ID rather than a placeholder."""
    cleaned = value.strip().lower()
    if cleaned in ANON_GENERIC_TOKENS:
        return False
    # Anonymised IDs generated by this pipeline start with "anon" (e.g. ANONCQSC6K1CD)
    if cleaned.startswith("anon"):
        return False
    # A real ID is typically numeric or alphanumeric and not a known word
    # Flag only if it contains digit sequences (typical for real MRNs/IDs)
    # while not matching known placeholders
    return bool(re.search(r"\d", cleaned))


def looks_like_real_date(value: str) -> bool:
    """
    Return True if the value looks like a real specific date.
    Anonymisers often zero out dates (19000101, 00000000) or leave blank.
    """
    cleaned = value.strip()
    if not cleaned:
        return False
    # DICOM date format: YYYYMMDD
    # Zeroed-out or epoch dates are considered anonymised
    dummy_dates = {"00000000", "19000101", "10000101"}
    if cleaned in dummy_dates:
        return False
    # If it parses as a plausible real date (after 1900, not a dummy year) → flag it
    if re.match(r"^\d{8}$", cleaned):
        year = int(cleaned[:4])
        return year > 1900
    return True  # non-standard format, flag to be safe


def looks_like_real_generic(value: str) -> bool:
    """Generic check for free-text fields (age, weight, ethnicity, etc.)"""
    cleaned = value.strip().lower()
    return cleaned not in ANON_GENERIC_TOKENS and cleaned != ""


# ---------------------------------------------------------------------------
# Tag registry: each entry maps a tag to (display_name, checker_function)
# ---------------------------------------------------------------------------
PHI_TAGS = {
    (0x0010, 0x0010): ("Patient's Name",             looks_like_real_name),
    (0x0010, 0x0020): ("Patient ID",                 looks_like_real_id),
    (0x0010, 0x0030): ("Patient's Birth Date",        looks_like_real_date),
    (0x0010, 0x0040): ("Patient's Sex",
                        lambda v: v.strip().lower() not in ANON_SEX_VALUES),
    (0x0010, 0x1010): ("Patient's Age",              looks_like_real_generic),
    (0x0010, 0x1030): ("Patient's Weight",           looks_like_real_generic),
    (0x0010, 0x0050): ("Patient's Insurance Plan",   looks_like_real_generic),
    (0x0010, 0x1000): ("Other Patient IDs",          looks_like_real_id),
    (0x0010, 0x1001): ("Other Patient Names",        looks_like_real_name),
    (0x0010, 0x2160): ("Ethnic Group",               looks_like_real_generic),
}


def check_anonymisation(root_dir: str) -> None:
    """
    Recursively finds all .dcm files and checks DICOM anonymisation by:
    1. Reading (0012,0062) Patient Identity Removed flag
    2. Checking all "must be empty/anonymised" PHI tags regardless of the flag
    3. Flagging contradictions where the flag is YES but PHI tags appear to contain real data
    """
    root = Path(root_dir)
    if not root.exists():
        print(f"[ERROR] Directory not found: {root_dir}")
        sys.exit(1)

    dcm_files = sorted(root.rglob("*.dcm"))
    if not dcm_files:
        print(f"No .dcm files found under: {root_dir}")
        return

    print(f"Found {len(dcm_files)} DICOM file(s) under: {root_dir}\n")

    counts = {
        "fully_clean":      0,
        "contradiction":    0,
        "flag_missing":     0,
        "not_anonymised":   0,
        "errors":           0,
    }

    for path in dcm_files:
        display_path = str(path)
        if len(display_path) > 70:
            display_path = "..." + display_path[-69:]

        print(f"{'─' * 80}")
        print(f"FILE : {display_path}")

        try:
            metadata = pydicom.dcmread(str(path), stop_before_pixels=True)

            # --- (0012,0062) Patient Identity Removed ---
            flag_tag = pydicom.tag.Tag(0x0012, 0x0062)
            if flag_tag in metadata:
                flag_value = str(metadata[flag_tag].value).strip().upper()
                flag_yes = flag_value == "YES"
                flag_display = "YES" if flag_yes else f"NO (value='{metadata[flag_tag].value}')"
            else:
                flag_yes = False
                flag_display = "ABSENT"
            print(f"  (0012,0062) Patient Identity Removed : {flag_display}")

            # --- Check PHI tags with per-tag heuristics ---
            suspicious = []
            for (grp, elm), (name, checker) in PHI_TAGS.items():
                tag = pydicom.tag.Tag(grp, elm)
                if tag in metadata:
                    raw_value = str(metadata[tag].value)
                    if checker(raw_value):
                        suspicious.append((f"({grp:04X},{elm:04X})", name, raw_value))

            if suspicious:
                print(f"  Suspicious PHI tags ({len(suspicious)}):")
                for tag_str, name, value in suspicious:
                    print(f"    {tag_str}  {name:<35} = '{value}'")
            else:
                print(f"  PHI tags           : all appear anonymised")

            # --- Verdict ---
            if flag_yes and not suspicious:
                verdict = "FULLY ANONYMISED"
                counts["fully_clean"] += 1
            elif flag_yes and suspicious:
                verdict = "CONTRADICTION — flag says YES but real PHI detected"
                counts["contradiction"] += 1
            elif not flag_yes and not suspicious:
                verdict = "FLAG MISSING/NO — but no real PHI detected in checked tags"
                counts["flag_missing"] += 1
            else:
                verdict = "NOT ANONYMISED — flag not set and real PHI detected"
                counts["not_anonymised"] += 1

            print(f"  Verdict            : {verdict}")

        except InvalidDicomError:
            print(f"  [ERROR] Invalid DICOM file — skipped")
            counts["errors"] += 1
        except Exception as e:
            print(f"  [ERROR] {e}")
            counts["errors"] += 1

    total = len(dcm_files)
    print(f"\n{'=' * 80}")
    print(f"SUMMARY  ({total} file(s) scanned)")
    print(f"{'=' * 80}")
    print(f"  Fully anonymised                              : {counts['fully_clean']}")
    print(f"  Contradiction (flag YES but real PHI present) : {counts['contradiction']}")
    print(f"  Flag missing/NO but no real PHI detected      : {counts['flag_missing']}")
    print(f"  Not anonymised (flag not set + real PHI)      : {counts['not_anonymised']}")
    print(f"  Errors / skipped                              : {counts['errors']}")